<a href="https://colab.research.google.com/github/sarishma123/PYTHON_4TH-SEM/blob/main/part2ofsarishma2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing numpy

In [ ]:
import numpy as np;

uisng arange function and reshape function

In [ ]:
arr = np.arange(1, 121).reshape(2, 3, 4, 5)
arr.shape

(2, 3, 4, 5)

In [ ]:
arr[1:2]

array([[[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [ ]:
arr[0,2]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [ ]:
arr[:,:,-1:,:]

array([[[[ 16,  17,  18,  19,  20]],

        [[ 36,  37,  38,  39,  40]],

        [[ 56,  57,  58,  59,  60]]],


       [[[ 76,  77,  78,  79,  80]],

        [[ 96,  97,  98,  99, 100]],

        [[116, 117, 118, 119, 120]]]])

In [ ]:
arr[:,:,:,::4]

array([[[[  1,   5],
         [  6,  10],
         [ 11,  15],
         [ 16,  20]],

        [[ 21,  25],
         [ 26,  30],
         [ 31,  35],
         [ 36,  40]],

        [[ 41,  45],
         [ 46,  50],
         [ 51,  55],
         [ 56,  60]]],


       [[[ 61,  65],
         [ 66,  70],
         [ 71,  75],
         [ 76,  80]],

        [[ 81,  85],
         [ 86,  90],
         [ 91,  95],
         [ 96, 100]],

        [[101, 105],
         [106, 110],
         [111, 115],
         [116, 120]]]])

In [ ]:
arr[:,:,-1,:]=0

In [ ]:
arr[:,:,-1,:]

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [ ]:
arr[0]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [ 0,  0,  0,  0,  0]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [ 0,  0,  0,  0,  0]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [ 0,  0,  0,  0,  0]]])

In [ ]:
arr[0]=-1