<a href="https://colab.research.google.com/github/sarishma123/PYTHON_4TH-SEM/blob/main/sarishmaday2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.importing the numpy


In [5]:
import numpy as np

BROADCASTING

2.knowing the dimension of array
and second rule of broadcasting


In [ ]:
h=np.arange(5).reshape(1,1,5)
h+[10,20,30,40,50]
print("the shape of this is:",h.shape)
print("the dimension is: ", h.ndim)

the shape of this is: (1, 1, 5)
the dimension is:  3


3.third rule as 1 and 2 rule of the size of all array must match


In [ ]:
a=[1,2]
b=[[1,2]]
print("the dimension of a is :", np.array(a).ndim)
print("the dimension of b is :", np.array(b).ndim)
print("the shape of a is :", np.array(a).shape)
print("the shape of b is :", np.array(b).shape)

the dimension of a is : 1
the dimension of b is : 2
the shape of a is : (2,)
the shape of b is : (1, 2)


*.Pratice question after 3rd rules

1.create a array and using broadcasting adding to 10 to every element


In [ ]:
arr=np.array([5,10,15,20,25])
result=arr+10
print("the result is:",result)

the result is: [15 20 25 30 35]


2.create the matrix and using broadcasting,add the row vector  ti every row

In [ ]:
matrix= np.array([[1,2,3],[4,5,6],[7,8,9]])
row_vector=np.array([10,20,30])
result=matrix+row_vector
print("the result is:",result)

the result is: [[11 22 33]
 [14 25 36]
 [17 28 39]]


3.create matrix and using broadcasting add the column verctor


In [ ]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
col_vector=np.array([[1],[2],[3]])
result=arr1+col_vector
print("the result is:",result)

the result is: [[11 21 31]
 [42 52 62]
 [73 83 93]]


4.create matrix and uisng broadcasting,create a matrix where every elemnt is the sum of one value from A and one from B

In [ ]:
A=np.array([1,2,3])
B=np.array([10,20,30,40])
result=A[:,np.newaxis]+B
print("the result is:",result)


the result is: [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


5.Create the matrix and calculate the average of the student after the bonous added..bonus for each subject is [5,3,2]

In [ ]:
A=np.array([[65,70,75],[80,85,90],[55,60,65],[95,90,85]])
bonus=np.array([5,3,2])
result=A+bonus
print("the result is:",result)


the result is: [[ 70  73  77]
 [ 85  88  92]
 [ 60  63  67]
 [100  93  87]]


UPCASTING


1.knowing the uint dataype and others

In [ ]:
k1 = np.arange(0, 5, dtype=np.uint8)
k2 = np.arange(5, 10, dtype=np.int64)

# Print the array values
print("Array:", k2)

# Print the data type
print("Data type:", k2.dtype)

Array: [5 6 7 8 9]
Data type: int64


Mathetical and statical function for differnt variable

In [6]:
m=np.array([[-2.5,3.1,7],[10,11,12]])
for func in(m.min,m.max,m.sum,m.std,m.var,m.mean):
  print(func.__name__,"=",func())

min = -2.5
max = 12.0
sum = 40.6
std = 5.084835843520964
var = 25.855555555555554
mean = 6.766666666666667


using arange and reshape

In [9]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
c.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [11]:
c.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [12]:
c.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [13]:
c.sum(axis=(0,2))

array([ 60,  92, 124])

In [14]:
a = np.array([[-2.5, 3.1, 7],
              [10, 11, 12]])

print("Original ndarray")
print(a)

for func in (np.square, np.abs, np.sqrt, np.exp, np.log,
             np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 square
[[  6.25   9.61  49.  ]
 [100.   121.   144.  ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


/tmp/ipykernel_496/2811277884.py:10: RuntimeWarning: invalid value encountered in sqrt
  print(func(a))
/tmp/ipykernel_496/2811277884.py:10: RuntimeWarning: invalid value encountered in log
  print(func(a))


In [15]:
a=np.array([1,5,3,19,13,7,3])
a[3]

np.int64(19)

In [16]:
a[2:5]

array([ 3, 19, 13])

In [17]:
a[2:-1]

array([ 3, 19, 13,  7])

In [18]:
a[:2]

array([1, 5])

In [19]:
a[2::2]

array([ 3, 13,  3])

In [20]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [21]:
a[::3]

array([ 1, 19,  3])

In [22]:
a=np.array([1,5,3,19,13,7,3])
a_slice=a[2:6]
a_slice[1]=1000
a

array([   1,    5,    3, 1000,   13,    7,    3])

In [23]:
another_slice=a[2:6].copy()
another_slice[1]=3000
a

array([   1,    5,    3, 1000,   13,    7,    3])

In [24]:
b=np.arange(48).reshape(4,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [25]:
b[1,2]

np.int64(14)

In [26]:
b[1,:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [27]:
b[:,1]

array([ 1, 13, 25, 37])

In [28]:
b[1:2,:]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [29]:
b[2:4,:]

array([[24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [30]:
b[2:,:]

array([[24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [31]:
b=np.arange(48).reshape(4,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [32]:
b[(0,2),2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

In [33]:
b[:,(-1,2,-1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [34]:
b[(-1,2,-1,2),(5,9,1,9)]

array([41, 33, 37, 33])

In [35]:
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
arr[0,:]

array([10, 20, 30])

In [36]:
arr[1,:]

array([40, 50, 60])

In [37]:
arr[:]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [38]:
arr[:,-1]

array([30, 60, 90])

In [39]:
arr[0,1]

np.int64(20)

In [40]:
arr[:,(0,1)]

array([[10, 20],
       [40, 50],
       [70, 80]])

In [41]:
arr[1:,1:]

array([[50, 60],
       [80, 90]])

In [42]:
c=np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [43]:
c[0:,0:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [44]:
c[0:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [45]:
c[0,:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
c[0,1,:]

array([5, 6, 7, 8])

In [47]:
c[:,:,-1]

array([[ 4,  8, 12],
       [16, 20, 24]])

In [48]:
c[0,:,-1]

array([ 4,  8, 12])

In [49]:
c[1,-1,-1]

np.int64(24)

In [50]:
c[1,:,:2]

array([[13, 14],
       [17, 18],
       [21, 22]])

In [51]:
q1=np.full((3,4),1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
q2=np.full((4,4),2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [53]:
q3=np.full((3,4),3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [54]:
q4=np.vstack((q1,q2,q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [55]:
q5=np.hstack((q1,q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [56]:
q8=np.stack((q1,q3))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [57]:
q8.shape

(2, 3, 4)

In [58]:
arr = np.arange(1, 49).reshape(2, 2, 3, 4)
arr[0]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [59]:
arr[0,1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [60]:
arr[1,1,2]

array([45, 46, 47, 48])

In [61]:
arr[0,:,:,-1]

array([[ 4,  8, 12],
       [16, 20, 24]])

In [62]:
arr[-1,-1,-1,-1]

np.int64(48)

In [63]:
arr[1,1,:,:2]

array([[37, 38],
       [41, 42],
       [45, 46]])

In [64]:
arr=np.arange(1,97).reshape(2,3,4,4)
arr[1,:,:,:]

array([[[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]],

       [[65, 66, 67, 68],
        [69, 70, 71, 72],
        [73, 74, 75, 76],
        [77, 78, 79, 80]],

       [[81, 82, 83, 84],
        [85, 86, 87, 88],
        [89, 90, 91, 92],
        [93, 94, 95, 96]]])

In [65]:
arr[:,:,:2,:]

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]],

        [[33, 34, 35, 36],
         [37, 38, 39, 40]]],


       [[[49, 50, 51, 52],
         [53, 54, 55, 56]],

        [[65, 66, 67, 68],
         [69, 70, 71, 72]],

        [[81, 82, 83, 84],
         [85, 86, 87, 88]]]])

In [66]:
arr[:,:,:,-2:]

array([[[[ 3,  4],
         [ 7,  8],
         [11, 12],
         [15, 16]],

        [[19, 20],
         [23, 24],
         [27, 28],
         [31, 32]],

        [[35, 36],
         [39, 40],
         [43, 44],
         [47, 48]]],


       [[[51, 52],
         [55, 56],
         [59, 60],
         [63, 64]],

        [[67, 68],
         [71, 72],
         [75, 76],
         [79, 80]],

        [[83, 84],
         [87, 88],
         [91, 92],
         [95, 96]]]])

In [67]:
arr[:,:,::2,:]

array([[[[ 1,  2,  3,  4],
         [ 9, 10, 11, 12]],

        [[17, 18, 19, 20],
         [25, 26, 27, 28]],

        [[33, 34, 35, 36],
         [41, 42, 43, 44]]],


       [[[49, 50, 51, 52],
         [57, 58, 59, 60]],

        [[65, 66, 67, 68],
         [73, 74, 75, 76]],

        [[81, 82, 83, 84],
         [89, 90, 91, 92]]]])

In [68]:
arr[:,:,1:3,1:3]

array([[[[ 6,  7],
         [10, 11]],

        [[22, 23],
         [26, 27]],

        [[38, 39],
         [42, 43]]],


       [[[54, 55],
         [58, 59]],

        [[70, 71],
         [74, 75]],

        [[86, 87],
         [90, 91]]]])