<a href="https://colab.research.google.com/github/sarishma123/PYTHON_4TH-SEM/blob/main/day3ofnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np;

In [3]:
r = np.arange(6).reshape(2, 3)
print(r)

[[0 1 2]
 [3 4 5]]


In [7]:
r1 = np.arange(24).reshape(6, 4)
r1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
r2 = np.arange(24).reshape(4, 6)
r2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
r3 = np.arange(15).reshape(3, 5)
r3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
r1,r2,r3=np.split(r,[1,3])
print(r1,r2,r3)

[[0 1 2]] [[3 4 5]] []


In [27]:
a=np.hstack(r1,r2,r2)
a

TypeError: hstack() takes 1 positional argument but 3 were given

In [11]:
a=np.vstack((r1,r2,r3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
m=np.matrix([[1,2],[3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [23]:
m = np.array([[1, 2],
              [3, 4]])
m_transpose = m.T
print("Original 2x2:\n", m)
print("\nTransposed 2x2:\n", m_transpose)

Original 2x2:
 [[1 2]
 [3 4]]

Transposed 2x2:
 [[1 3]
 [2 4]]


In [28]:
# Create a 3x3 matrix (1 through 9)
m= np.arange(1, 10).reshape(3, 3)

# Transpose
m_transpose = m.T

print("Original 3x3:\n", m)
print("\nTransposed 3x3:\n", m_transpose)

Original 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed 3x3:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [29]:
m1=m.reshape(3,3)
m1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
t=np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [37]:
t = np.arange(24).reshape(4, 2, 3)

# Use t.T (no parentheses) OR t.transpose()
t2 = t.T

print("original is the:\n", t)
print("\ntranspose is the:\n", t2)

original is the:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]

transpose is the:
 [[[ 0  6 12 18]
  [ 3  9 15 21]]

 [[ 1  7 13 19]
  [ 4 10 16 22]]

 [[ 2  8 14 20]
  [ 5 11 17 23]]]


In [43]:
n1 = np.arange(10).reshape(2, 5)
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
array=np.array([[1,2,3],[3,4,5],[6,7,8],[9,10,11],[14,15,16]])
array

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [14, 15, 16]])

In [44]:

n1 = np.arange(10).reshape(2, 5)

n2 = np.arange(10).reshape(5, 2)

# Method 1: @ operator
result1 = n1 @ n2

# Method 2: np.dot() function
result2 = np.dot(n1, n2)

print("n1 (2x5):\n", n1)
print("\nn2 (5x2):\n", n2)
print("\nDot Product result (2x2):\n", result1)

n1 (2x5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]

n2 (5x2):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Dot Product result (2x2):
 [[ 60  70]
 [160 195]]


In [46]:

# A square 2x2 matrix
A = np.array([[1, 2],
              [3, 4]])

# Compute Inverse
A_inv = np.linalg.inv(A)
print("Inverse Matrix:\n", A_inv)


Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [50]:
A = np.array([[1, 2, 3],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11],
              [12, 15, 16]])

det_A = np.linalg.det(A_square)
print("Determinant of first 3x3 block:", det_A)

Determinant of first 3x3 block: 0.0


In [51]:
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])

# Solve for x and y
solution = np.linalg.solve(A, b)
print("Solution [x, y]:", solution)  # Output: [1. 2.]

Solution [x, y]: [1. 2.]


In [52]:

A = np.array([[4, -2],
              [1,  1]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors (in columns):\n", eigenvectors)

Eigenvalues:
 [3. 2.]

Eigenvectors (in columns):
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
